version: "3"

volumes:
  db-data:
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"